// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKBcHH701mc1jQmcrWB9e6NI_UQz2Ns3g',
    appId: '1:481804233794:web:574a7b6476fc73a58611db',
    messagingSenderId: '481804233794',
    projectId: 'kecgo-9fdb3',
    authDomain: 'kecgo-9fdb3.firebaseapp.com',
    storageBucket: 'kecgo-9fdb3.appspot.com',
    measurementId: 'G-8R1HEP2FZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmOzwBpCqGtMSYtEj5AmAi_HRLPdtEryY',
    appId: '1:481804233794:android:16ebbe92a8d5f3ee8611db',
    messagingSenderId: '481804233794',
    projectId: 'kecgo-9fdb3',
    storageBucket: 'kecgo-9fdb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsgHQPaMa6oGLQk704ZJQEwRRdOBsJcIo',
    appId: '1:481804233794:ios:c13a54531ec89bb88611db',
    messagingSenderId: '481804233794',
    projectId: 'kecgo-9fdb3',
    storageBucket: 'kecgo-9fdb3.appspot.com',
    iosBundleId: 'com.example.kecapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsgHQPaMa6oGLQk704ZJQEwRRdOBsJcIo',
    appId: '1:481804233794:ios:c13a54531ec89bb88611db',
    messagingSenderId: '481804233794',
    projectId: 'kecgo-9fdb3',
    storageBucket: 'kecgo-9fdb3.appspot.com',
    iosBundleId: 'com.example.kecapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKBcHH701mc1jQmcrWB9e6NI_UQz2Ns3g',
    appId: '1:481804233794:web:910af7ba5ef42c988611db',
    messagingSenderId: '481804233794',
    projectId: 'kecgo-9fdb3',
    authDomain: 'kecgo-9fdb3.firebaseapp.com',
    storageBucket: 'kecgo-9fdb3.appspot.com',
    measurementId: 'G-TZY2WP4XXD',
  );
}
